#!/bin/bash
#
# File: /usr/local/bin/compton_prefs
# Based on: https://wiki.archlinux.org/index.php/Compton#Command_only
#
# How to use this file to type as little as possible when starting Compton:
#
#     $ git clone https://github.com/bengudro/configfiles.git
#     $ sudo mkdir -p /usr/local/bin
#     $ sudo cp configfiles/compton_prefs /usr/local/bin
#     $ rm -rf configfiles
#     $ cd /usr/local/bin
#     $ sudo ln -s compton_prefs c
#     $ cd
#
# Now, as my normal user, I can start compton by simply typing “c”-<RETURN>
# (without the quotes) in my favorite program-launcher (for example via
# <Ctrl>+<F2> in Gnome/KDE, or via <Mod>+“p” for dmenu in i3, or what have you…
#
# I could also auto-launch Compton using my WM/DE, but I like having the
# flexibilty to kill/re-launch Compton by a simple command whenever I feel like
# it  :)
compton --shadow			\
	--no-dock-shadow		\
	--no-dnd-shadow			\
	--fading			\
	--shadow-opacity	0.38	\
	--fade-out-step		200	\
	--fade-in-step		200	\
	--shadow-offset-y	0	\
	--shadow-offset-x	0	\
	--shadow-radius		3	\
	--fade-delta		2	\
	--menu-opacity		0.88	\
	--vsync			opengl	\
	--daemon

# vim:ts=8 sw=8 noet
